name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS gihub action credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: testing AWS CLI
        run: |
          aws ec2 describe-instances
      - name: deploying kubernete infra manifest
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/bitnami/ticketing-app
            git remote add origin https://github.com/youbihi/ticketing-app.git
            git fetch origin
            git checkout origin/master -- infra/k8s
            git checkout origin/master -- infra/k8s-prod
            cd /home/bitnami/ticketing-app/infra/k8s
            kubectl apply -f .
            cd /home/bitnami/ticketing-app/infra/k8s-prod
            kubectl apply -f .
          host: ${{ secrets.KOPS_PUBLIC_DNS }}
          user: bitnami
          key: ${{ secrets.MICROSERVICE_KOPS_KEYPAIR}}
