name: deploy-expiration

on:
  push:
    branches:
      - master
    paths:
      - 'expiration/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd expiration && docker build -t youbihi/expiration .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - run: docker push youbihi/expiration
      - name: SSH connexion and deploing expiration
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/bitnami/ticketing-app/infra/k8s
            kubectl apply -f .
          host: ${{ secrets.KOPS_PUBLIC_DNS }}
          user: bitnami
          key: ${{ secrets.MICROSERVICE_KOPS_KEYPAIR}}
