name: deploy-client

on:
  push:
    branches:
      - master
    paths:
      - 'client/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && docker build -t youbihi/client .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - run: docker push youbihi/client
      - name: ls after SSH connexion
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/bitnami/ticketing-app/infra/k8s
            kubectl apply -f .
            kubectl rollout restart deployment client-depl
          host: ${{ secrets.KOPS_PUBLIC_DNS }}
          user: bitnami
          key: ${{ secrets.MICROSERVICE_KOPS_KEYPAIR}}
