name: deploy-orders

on:
  push:
    branches:
      - master
    paths:
      - 'orders/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && docker build -t youbihi/orders .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - run: docker push youbihi/orders
      - name: SSH connexion and deploing orders
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/bitnami/ticketing-app/infra/k8s
            kubectl apply -f orders-depl.yaml
            kubectl rollout restart deployment orders-depl.yaml
          host: ${{ secrets.KOPS_PUBLIC_DNS }}
          user: bitnami
          key: ${{ secrets.MICROSERVICE_KOPS_KEYPAIR}}
