name: deploy-tickets

on:
  push:
    branches:
      - master
    paths:
      - 'tickets/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && docker build -t youbihi/tickets .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - run: docker push youbihi/tickets
      - name: SSH connexion and deploing ticket
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/bitnami/ticketing-app/infra/k8s
             kubectl apply -f tickets-depl.yaml
            kubectl rollout restart deployment tickets-depl.yaml
          host: ${{ secrets.KOPS_PUBLIC_DNS }}
          user: bitnami
          key: ${{ secrets.MICROSERVICE_KOPS_KEYPAIR}}
